export interface ICandidate {
  id:number
  name?:string
  fname?:string
  lname?:string
  description?:string
  position?:string;
  startDate?:Date;
  availabilityDate?:Date;
  jobtype?:string;
  contract?:string;
  workexperience?:number;
  language?:string[];
  mainskills?:string[];
  gender?:string;
  age?:number;
  photoURL?:string
  location?:string;
}
