export abstract class OptionsOfJobsAndCandidate {
  constructor() {
  }
  static JobType: string[] = [
    'Full Time',
    'Part Time',
    'Temporary',
  ];
  static JobPosition: string[] = [
    'Domestic Helper',
    'Driver',
  ];
  static Gender: string[] = [
    'Male',
    'Female',
    'Any'
  ];
  static ReligiousStatusOptions: string[] = [
    'Christianity',
    'Islam',
    'Judaism',
    'Hinduism',
    'Buddhism',
    'Sikhism',
    'Jainism',
    'Atheism',
    'Agnosticism',
    'Other (please specify)',
  ];
  static EducationStatusOptions: string[] = [
    'No formal education',
    'Primary education',
    'Secondary education',
    'Vocational qualification',
    "Bachelor's degree",
    "Master's degree",
    'Doctorate or equivalent',
    // Add more education level options as needed
  ];
  static OtherSkillsStatus: string[] = [
    'care giver',
    'car wash',
    'computer',
    'driving license',
    'first aid',
    'gardening',
    'handy man',
    'house work',
    'sewing',
  ];
  static PersonalitySkillsStatus = [
    'Communication skills',
    'Empathy',
    'Active listening',
    'Adaptability',
    'Problem-solving',
    'Conflict resolution',
    'Patience',
    'Flexibility',
    'Humility',
    'Emotional intelligence',
    'Time management',
    'Stress management',
    'Self-motivation',
    'Attention to detail',
    'Professionalism',
    'Cultural competence',
    'Tolerance',
    'Kindness',
    'Respect',
    'Trustworthiness',
  ];
  static MainSkillsStatus: string[] = [
    'Cleaning',
    'Cooking',
    'Laundry',
    'Ironing',
    'Childcare',
    'Elderly care',
    'Pet care',
    'Grocery shopping',
    'Meal planning',
    'Organizing',
    'Household management',
    'Communication skills',
    'Time management',
    'Basic first aid',
    'Driving',
  ];
  static cookingSkillsStatus: string[] = [
    'Food preparation',
    'Knife skills',
    'Meal planning',
    'Recipe following',
    'Baking',
    'Grilling',
    'Sauteing',
    'Boiling',
    'Steaming',
    'Roasting',
    'Frying',
    'Food presentation',
    'Understanding of flavors and seasonings',
    'Ingredient selection and storage',
    'Kitchen safety and hygiene',
    'Menu development',
    'Culinary creativity',
    'Adaptability to dietary restrictions',
    'Knowledge of different cuisines',
    'Plating and garnishing',
    'Time management in the kitchen',
    'Cleaning and maintenance of kitchen equipment',
    'Food preservation techniques',
  ];
  static LanguageStatus: string[] = [
    'arabic',
    'philipo',
    'Mandarin Chinese',
    'Japanese',
    'Korean',
    'Cantonese Chinese',
    'hindi',
    'Vietnamese',
    'Taiwanese Hokkien',
    'Tagalog (Filipino)',
    'Thai',
    'Burmese',
    'Khmer (Cambodian)',
    'Malay',
    'Indonesian',
    'Hmong',
    'Lao',
    'Mongolian',
  ];
  static AccomodationPreferenceStatus: string[] = [
    'Live Out',
    'Flexible',
    'To be Discussed',
    'Live In - Separate room',
    'Live In - Shared Room',
    'Live In - Separate room',
    'Live In',
  ];
  static DayOffPreferenceStatus: string[] = [
    'flexible',
    'to be discussed',
    'Friday-Saturday',
    'Saturday-Sunday',
    'saturday',
    'sunday',
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
  ];
  static CurrentWorkStatus: string[] = [
    'Employed full-time',
    'Employed part-time',
    'Self-employed',
    'Unemployed',
    'Student',
    'Retired',
    'Freelancer',
    'Contractor',
    'Temporarily laid off',
    'Homemaker',
    'Volunteer',
    'Not working for personal reasons',
  ];
  static CurrencyStatus: string[] = [
    'US$',
    'HK$',
    'SG$',
    'MOP$',
    'SAR',
    'QAR',
    'KWD',
    'AED',
    'PHP',
    'IDR',
    'MYR',
    'TWD',
  ];
  static PreferredCandidatelocation: string[] = [
    'Only OverSeas',
    'Present In My Country',
    'Any Location',
  ];
  static PreferredContractStatus: string[] = [
    'Any Situation',
    'Finished Contract',
    'Terminated (Relocation / Financial)',
    'Terminated (Other)',
    'Break Contract',
    'Transfer',
    'Overseas',
  ];
}
